[package]
name = "smush_lut"
version = "0.2.0"
authors = ["SMG <>"]
edition = "2018"

[dependencies]
image = "0.23"
indoc = "1.0"
itertools = "0.10.0"
clap = "2.33"
tegra_swizzle = "0.2.0"
nutexb = "0.6.0"