[package]
name = "smush_lut"
version = "0.3.0"
authors = ["SMG <>"]
edition = "2018"

[dependencies]
image = "0.24.5"
clap = "3.1.6"
nutexb = "0.6.0"

[dev-dependencies]
indoc = "1.0"
approx = "0.5.1"