[package]
name = "smush_lut"
version = "0.1.0"
authors = ["SMG <>"]
edition = "2018"

[dependencies]
image = "0.23"
itertools = "0.10.0"
clap = "2.33"
nom = "6.1.0"

[dev-dependencies]
indoc = "1.0"

[lib]
name = "smush_lut"
path = "src/lib.rs"

[[bin]]
name = "smush_lut"
path = "src/main.rs"